"""Standard OpenSSH ``known_hosts`` file.

verified = roundtrip: every emitted entry is looked up again with ``ssh-keygen -F``, which is
OpenSSH's own known_hosts parser. See verify.py.

Termius stores these in a shape that maps one-to-one onto the OpenSSH line format::

    [marker] hostnames keytype+base64key [comment]

and the ``key`` field already carries its type prefix, so no reconstruction is needed.

There is no Termix target for this: its backend exposes no known_hosts import route. A plain
file is more portable anyway — ssh itself, XPipe, WindTerm and anything else that shells out to
OpenSSH will read it.
"""

from __future__ import annotations

from ..model import Model
from . import OutputFile, WriteContext


class KnownHostsWriter:
    name = "known-hosts"
    title = "OpenSSH known_hosts"
    verified = "roundtrip"

    def write(self, model: Model, ctx: WriteContext) -> list[OutputFile]:
        if not model.known_hosts:
            return []

        lines = [
            "# Generated by termius-export",
            "#",
            "# Merge into ~/.ssh/known_hosts, or keep separate and point ssh at it:",
            "#   ssh -o UserKnownHostsFile=<this file> ...",
            "#",
            "# Host keys are public data - this file holds no secrets.",
        ]
        lines += [entry.to_line() for entry in model.known_hosts]
        return [OutputFile(path="known_hosts", content="\n".join(lines) + "\n", mode=0o644)]
