"""OpenSSH client configuration.

verified = roundtrip: the output is parsed by ``ssh -G`` itself, and the hostname / port / user
it resolves are compared against the model for every host — for **every** ``Host`` pattern the
local ssh accepts, not just the first. See verify.py.

One caveat the label cannot carry on its own: which aliases ssh accepts depends on the C
library, not on OpenSSH. glibc takes a CJK destination under every locale; macOS refuses one
under any UTF-8 locale. That is why hosts whose alias is not ASCII get a second, ASCII-only
pattern rather than being validated only where they happen to work. See trap 5 in CLAUDE.md.
"""

from __future__ import annotations

from ..model import Model
from . import OutputFile, WriteContext


def _proxy_command(proxy) -> str:
    if not proxy or not proxy.host or not proxy.port:
        return ""
    # Use ncat's (nmap-ncat) --proxy-type form. The widely copy-pasted
    # `nc -X 5 -x host:port` is OpenBSD netcat syntax and does not work on distributions
    # where /usr/bin/nc comes from nmap-ncat, such as Fedora.
    kind = "socks5" if proxy.kind == "socks5" else "http"
    return f"ncat --proxy {proxy.host}:{proxy.port} --proxy-type {kind} %h %p"


def _quote_path(path: str) -> str:
    """Double-quote an ssh_config path argument, but only when it needs it.

    An unquoted path containing a space is not merely wrong for that host - ssh rejects the
    whole file: "keyword identityfile extra arguments at end of line". Every host in the
    export becomes unusable. Quoting fixes it; ssh resolves the quoted form with the space
    preserved.

    Quoting unconditionally would also be correct, but it would change the generated file for
    every existing Linux user for no benefit, so quote exactly the paths that need it.

    A path containing a literal double quote is not representable in ssh_config and is not
    handled: it is an illegal character in Windows paths and vanishingly rare on POSIX.
    """
    return f'"{path}"' if any(c.isspace() for c in path) else path


class OpenSshWriter:
    name = "openssh"
    title = "OpenSSH ~/.ssh/config"
    verified = "roundtrip"

    def write(self, model: Model, ctx: WriteContext) -> list[OutputFile]:
        lines = [
            "# Generated by termius-export",
            "#",
            "# IdentityFile paths point into this export's keys/ directory. If you move the",
            "# keys into ~/.ssh/, update these paths to match.",
        ]

        # Only explained when it actually happened, so an ASCII-only export stays as it was.
        if any(h.ascii_alias for h in model.hosts):
            lines += [
                "#",
                "# Some hosts carry a second, ASCII-only name. Whether ssh accepts a non-ASCII",
                "# destination depends on the C library: glibc takes one under any locale, macOS",
                "# refuses one under any UTF-8 locale. Both names work wherever the first does.",
            ]

        lines.append("")

        for h in model.hosts:
            # `Host` takes several patterns, so the original alias is never given up. The ASCII
            # one comes second on purpose: if the original ever becomes valid everywhere, the
            # file should not have quietly trained people onto the derived name.
            lines.append(f"Host {' '.join(h.aliases)}")
            if h.address:
                lines.append(f"    HostName {h.address}")
            if h.username:
                lines.append(f"    User {h.username}")
            if h.port != 22:
                lines.append(f"    Port {h.port}")

            key_path = ctx.key_path(h.key)
            if key_path:
                lines.append(f"    IdentityFile {_quote_path(key_path)}")
                if h.key.has_passphrase:
                    lines.append("    # this key is passphrase-protected")

            if h.proxy and h.proxy.username:
                lines.append("    # proxy requires authentication; credentials are in hosts.csv")
            pc = _proxy_command(h.proxy)
            if pc:
                lines.append(f"    ProxyCommand {pc}")

            if h.agent_forward:
                lines.append("    ForwardAgent yes")

            for f in h.forwards:
                if f.type == "Local":
                    lines.append(f"    LocalForward {f.bound_address}:{f.local_port} {f.target_host}:{f.target_port}")
                elif f.type == "Remote":
                    lines.append(f"    RemoteForward {f.bound_address}:{f.local_port} {f.target_host}:{f.target_port}")
                else:
                    lines.append(f"    DynamicForward {f.bound_address}:{f.local_port}")

            if h.label_was_empty:
                lines.append("    # source had no name; alias derived from the address, as Termius displays it")
            if not key_path and h.password:
                lines.append("    # password authentication; the password is in hosts.csv")
            lines.append("")

        return [OutputFile(path="sshconfig", content="\n".join(lines), mode=0o600)]
