"""OpenSSH client configuration.

verified = roundtrip: the output is parsed by ``ssh -G`` itself, and the hostname / port / user
it resolves are compared against the model for every host. See verify.py.
"""

from __future__ import annotations

from ..model import Model
from . import OutputFile, WriteContext


def _proxy_command(proxy) -> str:
    if not proxy or not proxy.host or not proxy.port:
        return ""
    # Use ncat's (nmap-ncat) --proxy-type form. The widely copy-pasted
    # `nc -X 5 -x host:port` is OpenBSD netcat syntax and does not work on distributions
    # where /usr/bin/nc comes from nmap-ncat, such as Fedora.
    kind = "socks5" if proxy.kind == "socks5" else "http"
    return f"ncat --proxy {proxy.host}:{proxy.port} --proxy-type {kind} %h %p"


class OpenSshWriter:
    name = "openssh"
    title = "OpenSSH ~/.ssh/config"
    verified = "roundtrip"

    def write(self, model: Model, ctx: WriteContext) -> list[OutputFile]:
        lines = [
            "# Generated by termius-export",
            "#",
            "# IdentityFile paths point into this export's keys/ directory. If you move the",
            "# keys into ~/.ssh/, update these paths to match.",
            "",
        ]

        for h in model.hosts:
            lines.append(f"Host {h.alias}")
            if h.address:
                lines.append(f"    HostName {h.address}")
            if h.username:
                lines.append(f"    User {h.username}")
            if h.port != 22:
                lines.append(f"    Port {h.port}")

            key_path = ctx.key_path(h.key)
            if key_path:
                lines.append(f"    IdentityFile {key_path}")
                if h.key.has_passphrase:
                    lines.append("    # this key is passphrase-protected")

            if h.proxy and h.proxy.username:
                lines.append("    # proxy requires authentication; credentials are in hosts.csv")
            pc = _proxy_command(h.proxy)
            if pc:
                lines.append(f"    ProxyCommand {pc}")

            if h.agent_forward:
                lines.append("    ForwardAgent yes")

            for f in h.forwards:
                if f.type == "Local":
                    lines.append(f"    LocalForward {f.bound_address}:{f.local_port} {f.target_host}:{f.target_port}")
                elif f.type == "Remote":
                    lines.append(f"    RemoteForward {f.bound_address}:{f.local_port} {f.target_host}:{f.target_port}")
                else:
                    lines.append(f"    DynamicForward {f.bound_address}:{f.local_port}")

            if h.label_was_empty:
                lines.append("    # source had no name; alias derived from the address, as Termius displays it")
            if not key_path and h.password:
                lines.append("    # password authentication; the password is in hosts.csv")
            lines.append("")

        return [OutputFile(path="sshconfig", content="\n".join(lines), mode=0o600)]
