"""Tabby profiles, to be merged into ~/.config/tabby/config.yaml.

verified = upstream-source

Field names and value domains come from Tabby's own type definitions, not from documentation
or guesswork::

    tabby-ssh/src/api/interfaces.ts
        SSHProfileOptions, ForwardedPortConfig, PortForwardType
    tabby-core/src/api/profileProvider.ts
        Profile
    tabby-core/src/services/profiles.service.ts
        profile.id = `${type}:custom:${slugify(name)}:${uuidv4()}`

No "import into a real Tabby and read it back" round-trip has been done, hence
upstream-source rather than roundtrip.

Only fields we can be certain about are emitted. algorithms / input / keepalive* and friends
are deliberately omitted so Tabby applies its own defaults — inventing values is far more
dangerous than leaving them out.

Note that Tabby natively supports httpProxyHost / socksProxyHost, so proxies do not have to be
downgraded to a ProxyCommand.
"""

from __future__ import annotations

import json
import re
import uuid

from ..model import Model
from . import OutputFile, WriteContext

_SLUGIFY_DROP = re.compile(r"[^\w\s-]")
_SLUGIFY_SPACE = re.compile(r"[\s_]+")


def _slugify(value: str) -> str:
    s = _SLUGIFY_DROP.sub("", str(value or "").strip().lower())
    return _SLUGIFY_SPACE.sub("-", s).strip("-")


def _scalar(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    # Always double-quote strings with JSON escaping: valid YAML in every case.
    return json.dumps(str(value), ensure_ascii=False)


def _to_yaml(node, indent: int = 0) -> str:
    pad = " " * indent
    if isinstance(node, list):
        if not node:
            return f"{pad}[]"
        out = []
        for item in node:
            if isinstance(item, (dict, list)):
                body = _to_yaml(item, indent + 2)
                out.append(f"{pad}-{body[indent + 1 :]}")
            else:
                out.append(f"{pad}- {_scalar(item)}")
        return "\n".join(out)
    if isinstance(node, dict):
        out = []
        for k, v in node.items():
            if isinstance(v, (dict, list)):
                if isinstance(v, list) and not v:
                    out.append(f"{pad}{k}: []")
                else:
                    out.append(f"{pad}{k}:\n{_to_yaml(v, indent + 2)}")
            else:
                out.append(f"{pad}{k}: {_scalar(v)}")
        return "\n".join(out)
    return f"{pad}{_scalar(node)}"


class TabbyWriter:
    name = "tabby"
    title = "Tabby profiles (config.yaml fragment)"
    verified = "upstream-source"

    def write(self, model: Model, ctx: WriteContext) -> list[OutputFile]:
        profiles = []
        for h in model.hosts:
            name = h.label or h.alias
            key_path = ctx.key_path(h.key)

            options = {
                "host": h.address,
                "port": h.port,
                "user": h.username,
                "auth": h.auth,  # null | password | publicKey | agent | keyboardInteractive
                "password": h.password if ctx.include_secrets else "",
                "privateKeys": [key_path] if key_path else [],
                "agentForward": h.agent_forward,
            }

            if h.proxy and h.proxy.kind == "http":
                options["httpProxyHost"] = h.proxy.host
                options["httpProxyPort"] = h.proxy.port
            elif h.proxy and h.proxy.kind == "socks5":
                options["socksProxyHost"] = h.proxy.host
                options["socksProxyPort"] = h.proxy.port

            if h.forwards:
                options["forwardedPorts"] = [
                    {
                        "type": f.type,  # PortForwardType: Local | Remote | Dynamic
                        "host": f.bound_address,
                        "port": f.local_port,
                        "targetAddress": f.target_host,
                        "targetPort": f.target_port,
                        "description": f.label,
                    }
                    for f in h.forwards
                ]

            profiles.append(
                {
                    "id": f"ssh:custom:{_slugify(name)}:{uuid.uuid4()}",
                    "type": "ssh",
                    "name": name,
                    "group": h.group or "",
                    "options": options,
                }
            )

        header = [
            "# Tabby profiles - generated by termius-export",
            "#",
            "# Usage: merge the entries below into the top-level `profiles` list in",
            "# ~/.config/tabby/config.yaml. Merge by hand; do not overwrite the whole list.",
            "#",
            "# Fields follow Tabby's upstream type definitions but have NOT been verified by",
            "# a round-trip import. Confirm one host connects before relying on the rest.",
            "#",
            "# Omitted fields (algorithms / keepalive* / x11 ...) fall back to Tabby defaults.",
            "",
            "profiles:",
        ]

        content = "\n".join(header) + "\n" + _to_yaml(profiles, 2) + "\n"
        return [OutputFile(path="tabby-profiles.yaml", content=content, mode=0o600)]
